#!/bin/bash

set -e

#
# Command Line Options
#

OPTS=`getopt -o dtp: --long no-docker,tag:,port: -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then
	echo "Failed parsing options." >&2
	exit 1
fi

eval set -- "$OPTS"

# disable mouting local docker socket in container
NO_DOCKER=false
# image name and tag
PODMAN_SH_IMAGE_TAG="otaviof/podman-sh:latest"

while true; do
	case "$1" in
		-d | --no-docker ) NO_DOCKER=true ; shift ;;
		-t | --tag ) PODMAN_SH_IMAGE_TAG="$2" ; shift ; shift ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

#
# Global Variables
#

# base directory, where all data will be placed upon
BASE_DIR="${HOME}/.podman"
# docker configuration directory
DOCKER_DIR="${HOME}/.docker"
# docker socket
DOCKER_SOCK="/var/run/docker.sock"
# bash directory, to save histfile
BASH_DIR="${BASE_DIR}/bash.d"
# podman permanent storage
STORAGE_DIR="${BASE_DIR}/data"
# podman runtime storage
STORAGE_RUNTIME="${BASE_DIR}/runtime"
# container home directory
CONTAINER_HOME="/root"

# current directory name, to be mounted on container
CUR_DIR_NAME="$(basename ${PWD})"

# creating directories to be mounted on container
[ -d "${BASH_DIR}" ] || mkdir -v -p "${BASH_DIR}"
[ -d "${STORAGE_DIR}" ] || mkdir -v -p "${STORAGE_DIR}"
[ -d "${STORAGE_RUNTIME}" ] || mkdir -v -p "${STORAGE_RUNTIME}"
[ -d "${DOCKER_DIR}" ] || mkdir -v -p "${DOCKER_DIR}"

#
# Container Run
#

# using a empty string when docker socket should not be mounted
DOCKER_SOCK_MOUNT="--volume=${DOCKER_SOCK}:${DOCKER_SOCK}"
if [ $NO_DOCKER = true ] ; then
	DOCKER_SOCK_MOUNT=""
fi

cat <<EOS
#
# Podman development container for: '${CUR_DIR_NAME}' at '/src/${CUR_DIR_NAME}'
#
EOS

set -x
exec docker run \
	--name="${CUR_DIR_NAME}" \
	--interactive \
	--tty \
	--rm \
	--net="host" \
	--privileged \
	--cap-add="all" \
	--security-opt="label:disable" \
	--security-opt="seccomp:unconfined" \
	--env="HISTFILE=${CONTAINER_HOME}/.bash.d/histfile" \
	$DOCKER_SOCK_MOUNT \
	--volume="${DOCKER_DIR}:${CONTAINER_HOME}/.docker" \
	--volume="${BASH_DIR}:${CONTAINER_HOME}/.bash.d" \
	--volume="${STORAGE_DIR}:/var/lib/containers" \
	--volume="${STORAGE_RUNTIME}:/var/run/containers" \
	--volume="${PWD}:/src/${CUR_DIR_NAME}" \
	--workdir="/src/${CUR_DIR_NAME}" \
	${PODMAN_SH_IMAGE_TAG}
